#!/usr/bin/env bash
# Perform nginx server install and config

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html

# configure nginx server
default_sites="/etc/nginx/sites-available/default"
location=$(grep -Fn location $default_sites | head -1 | cut -d":" -f1)

## Update default site to redirect and start nginx server
sudo sed -i "${location}i ${location_data}" ${default_sites}
sudo service nginx start
