#!/usr/bin/env bash
#Task 4-TCP_and_UDP_ports
# A Bash script that displays listening ports:
# That only shows listening sockets
# That shows the PID and name of the program to which each socket belongs

sudo netstat -lp

